#!/bin/bash
# Generates 10 Sanad hero-template directions. ponytail: one throwaway script, delete after picking.
G="/Users/soudi/.claude/plugins/cache/ibrahim-plugins/nano-banana/2.1.0/scripts/genimage.py"
OUT="/Users/soudi/Sanad Marketing production 08.26/templates"
BRAND="Brand palette strictly: deep pine green #0C3B2E, muted gold #C9A24B, warm paper cream #F7F3EA, ink #10241E. Wordmark reads 'Sanad' in latin next to the Arabic word 'سند', with a small rounded square mark containing the Arabic letter 'س'. Top navigation links read 'How it works', 'Security', 'Pricing', 'FAQ' plus a small pill button reading 'عربي'. No stock photos of people, no medical or dental imagery, no syringes, no teeth, no doctors. No neon, no purple, no pink."

run () { python3 "$G" --prompt "$2" --output "$OUT/$1.png" --aspect-ratio 16:9 --resolution 2K > "$OUT/$1.log" 2>&1 & }

run 01-chrome-obsidian "Website hero section screenshot, desktop 16:9, for a B2B AI product. Near-black obsidian background. A large glossy chrome and frosted-glass 3D sculpture of a curved ribbon and floating capsule forms bleeds diagonally across the lower two thirds, lit with cool studio highlights and small warm gold light leaks. Enormous bold grotesk headline in two lines, tight tracking, centered: first line in white reading 'Your patients send voice notes.', second line in a soft gold-to-cream gradient reading 'Sanad listens and books them.' Below it a single line of small grey subtext reading 'Voice-first WhatsApp reception for Dubai dental and aesthetics clinics — 24/7, Arabic and English.' Two side-by-side outlined pill buttons with thin gold borders reading 'Book a demo' and 'Founding pricing'. Thin top navigation bar. At the very bottom edge, a faint horizontal marquee strip of repeating small text and a downward arrow. $BRAND"

run 02-pine-editorial "Website hero section screenshot, desktop 16:9. Deep pine green #0C3B2E full-bleed background with a subtle warm gold radial glow rising from the bottom. Two column layout. Left column: a small gold pill badge reading 'Dubai dental and aesthetics · 10 founding clinics · 40% off setup', then a very large elegant high-contrast serif headline in cream reading 'Your patients send voice notes. Sanad listens and books them.' with the words 'voice notes' underlined by a thick soft gold highlight bar, a short paragraph of muted sage body text below, and two buttons: a solid gold button reading 'See it on your own phone' and a ghost outlined cream button reading 'Founding pricing'. Right column: a realistic floating white smartphone mockup showing a WhatsApp chat, a green outgoing voice-note bubble with a waveform, and Arabic reply bubbles, with a small dark pill caption underneath reading 'Replied in seconds · booked at 9:48 PM'. Refined, calm, editorial, luxury SaaS. $BRAND"

run 03-vector-field "Website hero section screenshot, desktop 16:9. Background is a full-screen generative canvas of thousands of tiny short straight line segments arranged in a precise grid, each rotated to form a smooth flowing directional vector field, rendered in muted pine green and gold strokes on a very dark near-black pine background, with a bright warm gold swirl of longer highlighted strokes forming a circular disturbance near the centre right, as if a cursor pushed the field. Overlaid centred content: small gold monospace eyebrow text reading 'VOICE-FIRST AI RECEPTION', a huge bold uppercase headline in cream reading 'SANAD', a subheading reading 'Understands Gulf Arabic voice notes. Books into your calendar. Never medical advice.', and two outlined pill buttons reading 'Book a demo' and 'Security'. Technical, precise, generative-art. $BRAND"

run 04-paper-luxury "Website hero section screenshot, desktop 16:9. Warm paper cream #F7F3EA background with a very subtle paper grain texture and thin gold hairline rules framing the layout like a luxury print magazine. Centered composition: a small pine eyebrow with a short gold dash reading 'Dubai dental and aesthetics', then a very large elegant serif display headline in dark pine ink reading 'Your patients send voice notes. Sanad listens and books them.', a short centred paragraph of muted grey-green body text, and one solid pine green button reading 'See it on your own phone' beside a plain underlined text link reading 'Founding pricing'. Below the fold edge, a realistic white smartphone showing a WhatsApp conversation with Arabic bubbles casts a soft long shadow onto the cream, half cropped by the bottom of the frame. Quiet, expensive, editorial, lots of whitespace. $BRAND"

run 05-bento-dark "Website hero section screenshot, desktop 16:9. Dark pine green background. A modern bento grid of six rounded rectangular cards of different sizes with subtle 1px translucent cream borders and soft inner glows. Large top-left card holds the headline in cream serif reading 'Your patients send voice notes. Sanad listens and books them.' with a gold button reading 'Book a demo'. Tall right card holds a realistic WhatsApp chat mockup with a voice note waveform and Arabic reply bubbles. Small card shows a gold audio waveform and the label 'Voice notes, understood'. Small card shows a big tabular number '≈ AED 25,000' with the caption 'left unrecovered, monthly — illustrative'. Small card shows a calendar tile with a green check and the label 'Booked · tagged bot-originated'. Small card shows a UAE flag glyph and the label 'Patient data stays in the UAE'. Crisp, modern, dashboard-like, premium. $BRAND"

wait
run 06-waveform "Website hero section screenshot, desktop 16:9. Very dark pine, almost black, background. The dominant element is an enormous horizontal audio waveform spanning the entire width of the screen at mid height, made of hundreds of vertical rounded bars in gradient gold, brighter and taller in the centre, fading to dim pine at both edges, with a soft warm bloom behind it. Above the waveform, a large bold cream headline reading 'Seven seconds of Arabic, at 9:47 PM.' Below the waveform, a smaller cream subheading reading 'Sanad hears it, replies in seconds, and books the appointment.' and two buttons, one solid gold reading 'Hear it on your phone' and one ghost outlined reading 'How it works'. A small floating dark glass card near the right shows an Arabic WhatsApp reply bubble and a gold play triangle. Cinematic, dramatic, audio-first. $BRAND"

run 07-split-bilingual "Website hero section screenshot, desktop 16:9. A dramatic exact vertical split down the centre with a single thin gold divider line. Left half: deep pine green background, left-aligned English content, large cream serif headline reading 'Your patients send voice notes.', muted body text, and a gold button reading 'Book a demo'. Right half: warm paper cream background, right-aligned Arabic content in a clean modern Arabic typeface reading 'مرضاك يرسلون رسائل صوتية.' as a large dark pine headline, with muted Arabic body text beneath and a pine green button reading 'احجز عرضًا'. Straddling the divider in the exact centre, a single realistic floating white smartphone shows a WhatsApp chat with both English and Arabic bubbles, casting shadow onto both halves. Symmetrical, striking, bilingual-first. $BRAND"

run 08-brutalist "Website hero section screenshot, desktop 16:9. Brutalist high-contrast editorial layout. Warm paper cream background with thick 3px dark pine ink rules dividing the page into hard rectangular blocks. Oversized condensed uppercase headline in dark pine filling the top-left block reading 'NOBODY HEARS IT UNTIL MORNING'. A block on the right holds a giant monospace timestamp '21:47' in gold. A lower strip is a solid pine green bar containing small cream monospace text reading 'VOICE NOTES UNDERSTOOD / 24-7 / ARABIC + ENGLISH / NEVER MEDICAL ADVICE'. Another block holds tabular numbers laid out like a receipt: 'AED 400', 'x3 / DAY', '~21 DAYS', and a rule, then a large gold total '≈ AED 25,000'. A flat black rectangular button with cream monospace text reads 'BOOK A DEMO'. Raw, confident, typographic, no gradients, no rounded corners. $BRAND"

run 09-aurora-glass "Website hero section screenshot, desktop 16:9. Background is a deep pine-green to black aurora gradient with soft flowing bands of warm gold light and a fine grain overlay. Centered layout: a small translucent glass pill badge with a pulsing gold dot reading 'Founding cohort — 10 slots', a large cream serif headline reading 'A receptionist's night shift, without the night shift.', a short muted paragraph, and one solid gold button reading 'Book a demo' next to a glass outlined button reading 'Security'. In front, three overlapping frosted glassmorphic cards float at slight angles with heavy background blur and thin bright edge highlights: one shows a WhatsApp voice-note bubble with a waveform, one shows an Arabic reply bubble, one shows a calendar row with a green check reading 'Wed 7:15 PM · booked'. Soft, atmospheric, premium, depth of field. $BRAND"

run 10-clay-render "Website hero section screenshot, desktop 16:9. Warm paper cream background, soft studio lighting with gentle long shadows. Left side holds the text: a small gold eyebrow, a large dark pine serif headline reading 'Voice notes in. Appointments out.', a short muted paragraph, and a solid pine button reading 'See it on your own phone'. Right side is a playful 3D clay-render still-life floating in space: a rounded matte pine-green smartphone showing a simplified WhatsApp chat, a matte gold microphone icon, a cream calendar tile with a pine checkmark, and a small chrome-gold sound-wave arc, all with soft rounded edges, matte clay materials and subtle contact shadows, arranged in a loose diagonal cluster. Tactile, friendly, high-end 3D product illustration. $BRAND"

wait
echo DONE
